[project]
name = "qualibact-ref-qc"
version = "0.1.0"
description = "Environment for the dataset preparation helper"
channels = ["bioconda", "conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

[dependencies]
ncbi-datasets-cli = ">=18.9.0,<19"
python = ">=3.14.0,<3.15"
rich = "*"
art = ">=2016.6.5,<2017"

[tasks]
prepare-dataset = "python prepare_dataset.py"

[pypi-dependencies]
requests = ">=2.32.5, <3"
gdown = ">=5.2.0, <6"
matplotlib = ">=3.10.7, <4"
seaborn = ">=0.13.2, <0.14"
nf-core = ">=3.5.1, <4"
