[project]
name = "qualibact-ref-qc"
version = "0.1.0"
description = "Environment for the dataset preparation helper"
channels = ["bioconda", "conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

[dependencies]
ncbi-datasets-cli = ">=18.9.0,<19"
python = ">=3.14.0,<3.15"
rich = "*"
art = ">=2016.6.5,<2017"

[tasks]
prepare-dataset = "python prepare_dataset.py"
